### ISSUE TITLE
Apple Pay Button Style CSS is incorrect

### ISSUE THREAD

**Issue by webdevian** [Adyen/adyen-web#1225]
**Describe the bug**
In `@adyen/adyen-web/dist/adyen.css` the css rules for selecting apple pay button colour are as follows

```css
.ApplePayButton-module_apple-pay-button-black__3Ml54{
  -apple-pay-button-style:#000
}
.ApplePayButton-module_apple-pay-button-white__1qE8A{
  -apple-pay-button-style:#fff
}
.ApplePayButton-module_apple-pay-button-white-with-line__j9FE5{
  -apple-pay-button-style:white-outline
}
```

The hex values are not valid according to apples docs. They should be strings `black` or `white` - https://developer.apple.com/documentation/apple_pay_on_the_web/displaying_apple_pay_buttons_using_css

The values in the [source code](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/ApplePay/components/ApplePayButton.module.scss#L8) are strings so I believe a build process is setting them to the hex codes.
