### ISSUE TITLE
IFrame.scss styles not being applied

### ISSUE THREAD

**Issue by PG-RichT** [Adyen/adyen-web#2492]
**Describe the bug**
Following the removal of the inline IFrame styles in 5.52.0 (https://github.com/Adyen/adyen-web/pull/2343), the secure field iFrames are not rendering correctly, the IFrame.scss styles are not being applied. 

**To Reproduce**
1. Install Adyen Web NPM 5.51.0
2. Admire nicely styled secure fields
3. Upgrade to Adyen Web NPM 5.55.1
4. Cower in fear of the ugly, massive and unwieldy forms

**Expected behavior**
Should look like this:

![image](https://github.com/Adyen/adyen-web/assets/98329291/6f6e2871-fdbb-4b37-88da-d8d9c4922059)

Not this:

![image](https://github.com/Adyen/adyen-web/assets/98329291/4b939497-4ad7-498e-93b5-f3312d6ee46c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 120.0.6099.72

**Comment by longyulongyu** [comment]
@PG-RichT 
We moved the inline styles applied to iframe to separate scss files, could you check if you have imported the `adyen.css` file? 
Or you can add the following to your stylesheets as I see that you are doing customizations on the UI:
```css
.js-iframe {
    border: none;
    height: 100%;
    width: 100%;
    overflow: hidden;
}
.adyen-checkout__iframe{
    border: 0;
}
```
